# Go cross compiler (xgo): Go 1.13.x
# Copyright (c) 2019 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM pydio/xgo:1.13.15

LABEL maintainer="Pydio Team <team@pydio.com>"

