# Go cross compiler (xgo): Wildcard layer to the latest Go release
# Copyright (c) 2017 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM pydio/xgo:1.15.x

LABEL maintainer="Pydio Team <team@pydio.com>"
