# Go cross compiler (xgo): Go 1.12.12
# Copyright (c) 2019 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM pydio/xgo:1.12.13

LABEL maintainer="Pydio Team <team@pydio.com>"
